### PR TITLE
Square links

### PR DESCRIPTION
**Pull request by samlhuillier**
https://github.com/reorproject/reor/assets/17236551/1bf17371-5a48-4b1d-8112-a12f99c4c289

Implementation:
- Mostly implemented as a prosemirror extension in ```BacklinkExtension.tsx``` where double square brackets are detected and given custom html/css attributes.
- With custom html attribute we have a simple document listener in ```FileEditorContainer.tsx``` which calls open/create file from backlink
- Suggestions are done in ```BacklinkSuggestionDisplay.tsx```: the extension sets a state prop for what text is in the brackets and the position of the suggestions and the suggestion component filters files based on file name and displays them.

(This PR does not implement any logic around transitioning semantic links to backlinks. It just adds backlinks to work independently of semantic links.)

A small point on compatibility for users coming from Obsidian vaults:
- For files inside subfolders, obsidian can resolve the link [[filename]] if the path for filename is like ```folder1/filename``` whereas right now we can't. I would say that it's probably fine to go with this until we get asked to fix it

### CODE REVIEW

File: src/components/File/NewDirectory.tsx [hunk 1]
```diff
@@ -40,8 +40,8 @@ const NewDirectoryComponent: React.FC<NewDirectoryComponentProps> = ({
         return;
       }
       const normalizedDirectoryName = directoryName.replace(/\\/g, "/");
-      const fullPath = await window.files.joinPath(
-        window.electronStore.getUserDirectory(),
+      const fullPath = window.path.join(
```
Comment (chuyouchia) [inline src/components/File/NewDirectory.tsx:43]: Why was await removed? The IPC calls are all async afaik

File: electron/main/Generic/path.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+export function addExtensionToFilenameIfNoExtensionPresent(
+  filename: string,
+  extension: string
+): string {
+  const trimmedFilename = filename.trim();
+  const trimmedExtension = extension.trim();
+
+  if (!trimmedFilename || !trimmedExtension) {
+    return trimmedFilename;
+  }
```
Comment (chuyouchia) [inline electron/main/Generic/path.ts:12]: Nit: if !trimmedFilename, perhaps we should throw an error

File: src/components/Editor/BacklinkSuggestionsDisplay.tsx [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+
+  useEffect(() => {
+    if (
+      !suggestionsState.position ||
+      filteredSuggestions.length === 0 ||
+      !suggestionsRef.current
+    ) {
+      return;
+    }
+    const { top, left } = suggestionsState.position;
```
Comment (chuyouchia) [inline src/components/Editor/BacklinkSuggestionsDisplay.tsx:44]: Minor usability suggestion - we should have the bounding box for displays just outside of the square brackets, rather right next to the cursor. That makes it easier to edit 

image

File: src/components/Editor/BacklinkExtension.tsx [hunk 4]
```diff
@@ -0,0 +1,177 @@
...
+
+          const textToLeft = textBeforeCursor.slice(
+            lastOpeningBracketIndex + 2,
+            from
+          );
+
+          const coords = view.coordsAtPos(from);
+          updateSuggestionsState({
+            textWithinBrackets: textToLeft,
+            position: coords,
```
Comment (chuyouchia) [inline src/components/Editor/BacklinkExtension.tsx:59]: Re usability nit - Perhaps the coords here should use the back ]] square brackets

File: src/components/FileEditorContainer.tsx [hunk 5]
```diff
@@ -33,13 +36,33 @@ const FileEditorContainer: React.FC<FileEditorContainerProps> = () => {
...
+      }
+    };
+
+    document.addEventListener("click", handleClick);
+
+    return () => {
+      document.removeEventListener("click", handleClick);
+    };
+  }, [openRelativePath]);
+
```
Comment (chuyouchia) [inline src/components/FileEditorContainer.tsx:65]: Might not be possible depending on how the onClick render works with the HTML editor, but could we directly attach onClick listener to the backlink after the relative path is correctly set/selected? So we don't have to set this overarching useEffect that overrides the click handler.

Splitting this code logic is going to make it slightly harder to find where does the code for navigation live.

File: src/components/Editor/BacklinkExtension.tsx [hunk 6]
```diff
@@ -0,0 +1,177 @@
...
+                Decoration.inline(backlinkEnd, end, { style: bracketsStyle })
+              );
+
+              decorations.push(
+                Decoration.inline(backlinkStart, backlinkEnd, {
+                  style:
+                    "color: #92c8fc; text-decoration: underline; cursor: pointer;",
+                  "data-backlink": "true",
+                })
+              );
```
Comment (chuyouchia) [inline src/components/Editor/BacklinkExtension.tsx:126]: if we can set HTML directly, we may be able to set onClick listener too

File: electron/main/Generic/path.ts (hunk 2 above)
Comment (samlhuillier) [reply electron/main/Generic/path.ts]: Done

File: src/components/FileEditorContainer.tsx (hunk 5 above)
Comment (samlhuillier) [reply src/components/FileEditorContainer.tsx]: Fixed! Originally thought it may be difficult to do given that passing in the openfile to tiptap on init would not let it access the state the openfile function needs. Modified the code to ```useRef``` and it now works without document listener

File: src/components/Editor/BacklinkSuggestionsDisplay.tsx (hunk 3 above)
Comment (samlhuillier) [reply src/components/Editor/BacklinkSuggestionsDisplay.tsx:43]: done

File: src/components/Editor/BacklinkExtension.tsx (hunk 4 above)
Comment (samlhuillier) [reply src/components/Editor/BacklinkExtension.tsx:63]: very fiddly to do this correctly - for now just added an offset to the coordinate

**Review by chuyouchia — APPROVED** [review]

**Comment by chuyouchia** [comment]
Hmm just realized that links are not clickable now when I paste them into the notes
